version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    command: mongod --bind_ip_all
    ports:
      - "27018:27017"  
    volumes:
      - mongo_data:/data/db
    networks:
      - actus-network

  actus-riskserver-ce:
    image: actus-risksrv3-custom:latest
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    networks:
      - actus-network

  actus-server-rf20:
    image: actusfrf/actus-server-rf20:latest
    ports:
      - "8083:8083"
    networks:
      - actus-network

volumes:
  mongo_data:

networks:
  actus-network:
    driver: bridge
